
services:
  repetitor_backend:
    container_name: repetitor_backend
    image: repetitor_backend_image
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - "/backend/repetitor_backend:/$$(pwd)/repetitor_backend"
    env_file:
      - .env
    depends_on:
      - repetitor_db

  repetitor_bot:
    container_name: repetitor_bot
    image: repetitor_bot_image
    build:
      context: bot
      dockerfile: Dockerfile
    env_file:
      - ./.env

  repetitor_db:
    container_name: repetitor_db
    image: postgres:alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    env_file:
      - .env

  repetitor_django:
    container_name: repetitor_django
    image: django_image
    build: django/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/:/usr/src/django
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - repetitor_db

volumes:
  postgres_data:

